version : "3"
services:
  eureka:
    image: eureka:latest
    container_name: eureka
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=eureka
    networks:
      - spring
  blogs:
    image: blogs:latest
    container_name: blogs
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - spring
    depends_on:
      - eureka
  users:
    image: users:latest
    container_name: users
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - spring
    depends_on:
      - eureka
networks:
  spring:
    driver: bridge
